-- 1. PROFILES TABLE (Stays the same, linked to Auth)
CREATE TABLE profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT,
  avatar_url TEXT,
  notifications_enabled BOOLEAN DEFAULT TRUE,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. FOLDERS TABLE
create table public.folders (
  id integer generated by default as identity not null,
  user_id uuid not null,
  name text not null,
  color text null,
  created_at timestamp with time zone null default now(),
  constraint folders_pkey primary key (id),
  constraint folders_user_id_fkey foreign KEY (user_id) references auth.users (id) on delete CASCADE
) TABLESPACE pg_default;

-- 3. CATEGORIES_V2 TABLE
CREATE TABLE categories_v2 (
  id INT4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  folder_id INT4 REFERENCES folders ON DELETE SET NULL,
  name TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. TASKS_V2 TABLE
CREATE TABLE tasks_v2 (
  id INT4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  category_id INT4 REFERENCES categories_v2 ON DELETE SET NULL, -- Linked to v2 categories
  folder_id INT4 REFERENCES folders ON DELETE SET NULL, -- Direct link to folders
  title VARCHAR(255) NOT NULL,
  description TEXT,
  due_date DATE,
  priority INT4 DEFAULT 0,
  is_completed BOOL DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index for folder-based task filtering
CREATE INDEX idx_tasks_v2_folder_id ON tasks_v2(folder_id);

-- 5. INVITATIONS TABLE (Updated reference to v2)
CREATE TABLE invitations (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  category_id INT4 REFERENCES categories_v2 ON DELETE CASCADE NOT NULL,
  inviter_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  invitee_email TEXT NOT NULL,
  status TEXT CHECK (status IN ('pending', 'accepted', 'declined')) DEFAULT 'pending',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

---
-- RLS POLICIES FOR RENAMED TABLES
---
ALTER TABLE categories_v2 ENABLE ROW LEVEL SECURITY;
ALTER TABLE folders ENABLE ROW LEVEL SECURITY;
ALTER TABLE tasks_v2 ENABLE ROW LEVEL SECURITY;

-- Categories_v2 Policy
CREATE POLICY "Users can manage own categories_v2" 
ON categories_v2 FOR ALL 
USING (auth.uid() = user_id);

-- Folders Policy
CREATE POLICY "Users can manage own folders"
ON folders FOR ALL
USING (auth.uid() = user_id);

-- Tasks_v2 Policy
CREATE POLICY "Users can manage own tasks_v2" 
ON tasks_v2 FOR ALL 
USING (auth.uid() = user_id);

-- Profile & Invitation RLS (as defined previously)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE invitations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own profile" ON profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Inviter can manage sent invites" ON invitations FOR ALL USING (auth.uid() = inviter_id);
CREATE POLICY "Invitee can view received invites" ON invitations FOR SELECT USING (auth.jwt() ->> 'email' = invitee_email);